/*************************************************************
 *  This File define the structs
 *  Need by the main window
 *  Generated by mStudio
 *
 *  You can Modify this file
 *
 ***********************************************************/


#ifndef NCS_WINDOW_TYPES
#define NCS_WINDOW_TYPES

#ifdef __cplusplus
extern "C" {
#endif

 //TODO -- define you struct hear

extern HPACKAGE ghPkg;

extern mDataSource * gDs;

#define DSTYPE_TEXT 1
#define DSTYPE_ETC   2
#define DSTYPE_SQLITE 3
#define DSTYPE_XML 4

#ifdef __cplusplus
}
#endif

#endif /** NCS_WINDOW_TYPES*/
