/*************************************************************
 *  This File define the structs
 *  Need by the main window
 *  Generated by mStudio
 *
 *  You can Modify this file
 *
 ***********************************************************/


#ifndef NCS_WINDOW_TYPES
#define NCS_WINDOW_TYPES

#ifdef __cplusplus
extern "C" {
#endif

extern HPACKAGE hPackage;
 //TODO -- define you struct hear

#include "mobile-ime.h"
extern mMobileIMManager * immanger;

#ifdef __cplusplus
}
#endif

#endif /** NCS_WINDOW_TYPES*/
